TaskFlow/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls')),
    path('', include('dashboard.urls'))
]

dashboard/urls.py
from django.urls import path
from .views import  home_view, home_authenticated, create_card, create_dashboard

urlpatterns = [
    path('', view=home_view, name='home'),
    path('home/', view=home_authenticated, name="homepage"),
    path('create/', view=create_card, name="create_card"),
    path('dashboard/', view=create_dashboard, name="dashboard"),
]

authentication/models.py
from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser, PermissionsMixin
from django.utils import timezone

class UserManager(BaseUserManager):
  def create_user(self, name, email, password=None, **extra_fields):
    if name is None:
      raise ValueError('User must provide a name')
    if email is None:
      raise ValueError('User must provide an email')

    user = self.model(name=name, email=self.normalize_email(email), **extra_fields)
    user.set_password(password)
    user.save(using=self._db)
    return user

  def create_superuser(self, name, email, password=None, **extra_fields):
    extra_fields.setdefault('is_staff', True)
    extra_fields.setdefault('is_superuser', True)

    if extra_fields.get('is_staff') is not True:
      raise ValueError('O superusuário precisa ter is_staff=True.')
    if extra_fields.get('is_superuser') is not True:
      raise ValueError('O superusuário precisa ter is_superuser=True.')

    return self.create_user(name=name, email=email, password=password, **extra_fields)

class User(AbstractBaseUser, PermissionsMixin):
  user_id = models.AutoField(primary_key=True)
  name = models.CharField(max_length=255)
  email = models.EmailField(max_length=255, unique=True)
  password = models.CharField(max_length=255)
  is_superuser = models.BooleanField(default=False)
  is_staff = models.BooleanField(default=False)
  is_admin = models.BooleanField(default=False)

  USERNAME_FIELD = 'email'
  REQUIRED_FIELDS = ['name']

  objects = UserManager()

  def __str__(self):
    return self.name

class Board(models.Model):
  board_id = models.AutoField(primary_key=True)
  name = models.CharField(max_length=255)
  description = models.TextField()
  created_at = models.DateTimeField(default=timezone.now)
  user = models.ForeignKey(User, on_delete=models.CASCADE)

  def __str__(self):
      return self.name


class List(models.Model):
  list_id = models.AutoField(primary_key=True)
  name = models.CharField(max_length=255)
  description = models.TextField()
  board = models.ForeignKey(Board, on_delete=models.CASCADE)

  def __str__(self):
    return self.name

class EpicLink(models.Model):
  epic_link_id = models.AutoField(primary_key=True)
  name = models.CharField(max_length=255)
  description = models.TextField()

  def __str__(self):
    return self.name

class Card(models.Model):
  PRIORITY_CHOICES = [
    (0, 'Normal'),
    (1, 'Moderado'),
    (2, 'Alto'),
    (3, 'Muito Alto')
  ]
  card_id = models.AutoField(primary_key=True)
  title = models.CharField(max_length=255)
  description = models.TextField()
  creation_date = models.DateTimeField(default=timezone.now)
  delivery_date = models.DateTimeField(null=True, blank=True)
  priority = models.IntegerField(default=0, choices=PRIORITY_CHOICES)
  epic_link = models.ForeignKey(EpicLink, on_delete=models.CASCADE, blank=False)
  list = models.ForeignKey(List, on_delete=models.CASCADE)
  user = models.ForeignKey(User, on_delete=models.CASCADE)
  assigned = models.ForeignKey(User, on_delete=models.CASCADE, related_name='assigned_cards')



  def __str__(self):
    return self.title

  def get_priority_display(self):
    return dict(self.PRIORITY_CHOICES)[self.priority]

class Comment(models.Model):
  comment_id = models.AutoField(primary_key=True)
  content = models.TextField()
  comment_date = models.DateTimeField(default=timezone.now)
  user = models.ForeignKey(User, on_delete=models.CASCADE)
  card = models.ForeignKey(Card, on_delete=models.CASCADE)

class Attachment(models.Model):
  attachment_id = models.AutoField(primary_key=True)
  file_name = models.CharField(max_length=255)
  file_url = models.URLField()
  upload_date = models.DateTimeField(default=timezone.now)
  card = models.ForeignKey(Card, on_delete=models.CASCADE)

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/forms.py
from django import forms
from authentication.models import Card, EpicLink, List, User

class CardForm(forms.ModelForm):
    class Meta:
        model = Card
        fields = ['title', 'description', 'delivery_date', 'priority', 'epic_link', 'list', 'user']

    title = forms.CharField(max_length=255, widget=forms.TextInput(attrs={'placeholder': 'Insira o titulo....'}))
    description = forms.CharField(max_length=800, required=True, widget=forms.TextInput(attrs={'class': '.div-input-desc', 'placeholder': 'Insira a descrição....', }))
    delivery_date = forms.DateTimeField(
        widget=forms.DateInput(attrs={'type': 'datetime-local', 'class': 'teste', 'style': "background-color: #FFD6B1"}),
    )
    priority = forms.ChoiceField(
        choices=[('', 'Prioridade')] + list(Card.PRIORITY_CHOICES),
        widget=forms.Select(attrs={'style': "background-color: #ffb1b3; color: #9d2527"}),
        required=True,
    )
    epic_link = forms.ModelChoiceField(
        queryset=EpicLink.objects.all(),
        required=True,
        widget=forms.Select(attrs={'style': "background-color: #ffb1ff; color: #9d257d"}),
        empty_label="Epic Link"
    )
    list = forms.ModelChoiceField(queryset=List.objects.all())
    user = forms.ModelChoiceField(queryset=User.objects.all())
    assigned = forms.ModelChoiceField(queryset=User.objects.all(), required=True)

dashboard/views.py
from django.shortcuts import render, redirect
from authentication.models import List
from .forms import CardForm
from django.contrib import messages

def home_view(request):
  return render(request, 'index.html')

def home_authenticated(request):
    form = CardForm()
    listing = List.objects.all()
    context = {
        'list': listing,
        'form': form
    }
    return render(request, 'home.html', context=context)

def create_card(request):
    if request.method == 'POST':
        form = CardForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Card created successfully.')
        else:
            print(form.errors)
            messages.error(request, 'There was an error creating the card.')
    return redirect('homepage')


def create_dashboard(request):
    return render(request, 'dashboard.html')

dashboard/templates/aside.html
<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="Description of the page content" />
        <title>
            {% block title %}
            {% endblock title %}
        </title>
        {% load static %}
        <link rel="stylesheet" href="{% static 'styles/aside.css' %}" />
    </head>
    <body>
        <main>
            {% block content %}
            {% endblock content %}
        </main>
    </body>
</html>

dashboard/templates/dashboard.html
{% extends "aside.html" %}
{% load static %}
{% block content %}
    <div class="container">
        <!-- Sidebar -->
        <aside class="sidebar">
            <!-- Logo -->
            <div class="logo">
                <img src="{% static 'assets/LogoText.svg' %}"
                     alt="logo"
                     height="55px"
                     width="222px" />
            </div>
            <!-- User Profile -->
            <div class="user-profile">
                <img src="{% static 'assets/userImage.svg' %}"
                     alt="logo"
                     height="56px"
                     width="56px" />
                <div class="user-info">
                    <h3 class="user-name">Victor Hugo</h3>
                    <p class="user-role">Programador</p>
                </div>
                <button class="dropdown-button">
                    <span class="chevron-icon">
                        <img src="{% static 'assets/arrowDonw.svg' %}"
                             alt="logo"
                             width="12px"
                             height="6px" />
                    </span>
                </button>
            </div>
            <!-- Navigation -->
            <nav class="navigation">
                <div>
                    <h4 class="menu-title">Menu</h4>
                    <ul class="menu-list">
                        <li>
                            <a href="#" class="menu-item active">Início</a>
                        </li>
                        <li>
                            <a href="#" class="menu-item">Quadros</a>
                        </li>
                        <li>
                            <a href="#" class="menu-item">Colaboradores</a>
                        </li>
                        <li>
                            <a href="#" class="menu-item">Compromissos</a>
                        </li>
                        <li>
                            <a href="#" class="menu-item">Configurações</a>
                        </li>
                    </ul>
                </div>
                <div>
                    <h4 class="menu-title">Times</h4>
                    <ul class="menu-list">
                        <li>
                            <a href="#" class="menu-item">Pechinchou</a>
                        </li>
                        <li>
                            <a href="#" class="menu-item">Nadic</a>
                        </li>
                        <li>
                            <a href="#" class="menu-item">TCC</a>
                        </li>
                    </ul>
                </div>
            </nav>
        </aside>
        <!-- Main Content -->
        <main class="main-content">
            <div class="content-wrapper">
                <div class="dashboard-header">
                    <h1 class="dashboard-title">Dashboard</h1>
                </div>
                <div class="card-grid">
                    <div class="card frontend-card">Frontend</div>
                    <div class="card backend-card">Backend</div>
                    <div class="card new-board-card">Novo Quadro</div>
                </div>
            </div>
        </main>
    </div>
{% endblock content %}

dashboard/templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Dashboard</title>
    <link rel="stylesheet" href="{% static 'styles/homepage.css' %}" />
    <script src="{% static 'scripts/index.js' %}"></script>
    <meta name="description" content="Description of the page content" />
  </head>
  <body>
    <h1>Quadros</h1>
    <div class="content-cards">
      {% for list in list %}
      <div class="vertical-list">
        <h2 class="list-name">{{ list.name }}</h2>
        {% if list.card_set.exists %}
        <div class="cards-list">
          {% for card in list.card_set.all %}
          <div class="card-main">
            <div class="header-card">
              <div class="user-info">
                <img
                  src="{% static 'assets/userImage.svg' %}"
                  alt="logo"
                  height="25px"
                  width="25px"
                />
                <p>{{ card.user }}</p>
              </div>
              <div class="div-hours">
                <img
                  src="{% static 'assets/iconClock.svg' %}"
                  alt="logo"
                  height="16px"
                  width="16px"
                />
                <p>há {{ card.delivery_date|time:"H:i" }}</p>
              </div>
            </div>
            <div class="content-description">
              <h3 class="title-card">{{ card.title }}</h3>
              <p class="description">{{ card.description }}</p>
            </div>
            <div class="div-labels">
              <div class="label" style="background-color: #ffb1b1">
                <p>{{ card.get_priority_display }}</p>
              </div>
              <div class="label" style="background-color: #b1d3ff">
                <p>{{ card.epic_link }}</p>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
        {% else %}
        <div class="not-have-cards">
          <p>Não há cartões <strong>{{list.name}}</strong></p>
        </div>
        {% endif %}
        <button class="add-card" id="openModalBtn">
          <img
            src="{% static 'assets/iconPlus.svg' %}"
            alt="logo"
            height="20px"
            width="20px"
          />
          Novo
        </button>
      </div>
      {% endfor %}
    </div>

    <div id="myModal" class="modal">
      <div class="modal-content">
        <form
          class="form-register"
          method="post"
          action="{% url 'create_card' %}"
        >
          {% csrf_token %}
          <div class="header-modal">
            <div class="div-options">
              <div class="select-header">
                {{ form.epic_link }}
                <img
                  src="{% static 'assets/arrowDonw.svg' %}"
                  alt="arrow-donw"
                  width="10px"
                  height="5px"
                />
              </div>
              <div class="select-header">
                {{ form.priority }}
                <img
                  src="{% static 'assets/arrowDonw.svg' %}"
                  alt="arrow-donw"
                  width="10px"
                  height="5px"
                />
              </div>
              <div class="select-header">{{ form.delivery_date }}</div>
            </div>
            <span class="close">
              <img
                src="{% static 'assets/iconClose.svg' %}"
                alt="icon-close"
                width="24px"
                height="24px"
              />
            </span>
          </div>
          <div class="div-input">
            <label>Titulo</label>
            {{ form.title }}
          </div>
          <div class="row">
            <div class="div-input-select">
              <label>Responsável</label>
              {{ form.assigned }}
            </div>
            <div class="div-input-select">
              <label>Relator</label>
              {{ form.user }}
            </div>
            <div class="div-input-select">
              <label>Story Point</label>
              {{ form.list }}
            </div>
          </div>
          <div class="div-input-desc">
            <label>Descrição</label>
            {{ form.description }}
          </div>
          <div class="content-images">
            <label>Anexos</label>
            <div class="row-images">
              <div class="container-image">
                <div class="div-image"></div>
                <p>REMOVER</p>
              </div>
              <div class="container-image">
                <div class="div-image"></div>
                <p>REMOVER</p>
              </div>
            </div>
          </div>
          <button type="submit">SALVAR</button>
        </form>
      </div>
    </div>
  </body>
</html>

dashboard/templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="pt-br">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="Description of the page content" />
        <title>Tela</title>
        {% load static %}
        <link rel="stylesheet" href="{% static 'styles/home.css' %}" />
    </head>
    <body>
        <section class="container-1">
            <header>
                <a href="#">
                    <img src="{% static 'assets/Logo.svg' %}"
                         alt="logo"
                         height="auto"
                         width="auto" />
                </a>
                <nav>
                    <div class="div-button">
                        <img src="{% static 'assets/IconAbout.svg' %}"
                             alt="icon"
                             height="auto"
                             width="auto" />
                        <a href="">Sobre</a>
                    </div>
                    <div class="div-button">
                        <img src="{% static 'assets/IconSend.svg' %}"
                             alt="icon"
                             height="auto"
                             width="auto" />
                        <a href="">Contato</a>
                    </div>
                    <div class="div-button">
                        <img src="{% static 'assets/IconSmile.svg' %}"
                             alt="icon"
                             height="auto"
                             width="auto" />
                        <a href="">Ajuda</a>
                    </div>
                </nav>
                <div class="auth-buttons">
                    <div class="div-button">
                        <img src="{% static 'assets/iconLogin.svg' %}"
                             alt="icon"
                             height="auto"
                             width="auto" />
                        <a href="{% url 'login' %}">Entrar</a>
                    </div>
                    <div class="div-button">
                        <img src="{% static 'assets/IconUser.svg' %}"
                             alt="icon"
                             height="auto"
                             width="auto" />
                        <a href="{% url 'register' %}">Cadastrar</a>
                    </div>
                </div>
            </header>
            <div class="hero">
                <div class="div-texts">
                    <h1>
                        Transforme a <span class="span-1">colaboração</span> em
                        <span class="span-2">resultados</span>
                    </h1>
                    <p>
                        Organize tarefas em grupo com a metodologia scrum e alcance seus
                        ojetivos com agilidade e eficiência
                    </p>
                    <a href="{% url 'login' %}">
                        <button>Comece agora!</button>
                    </a>
                </div>
                <img src="{% static 'assets/Hero.svg' %}"
                     alt="img"
                     height="auto"
                     width="auto" />
            </div>
        </section>
        <section class="container-functions">
        </section>
    </body>
</html>